

version: 2.1



jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD


        
    step:
      - checkout
      - run:
          name : raise message
          command: |
            echo 'this code runs properly'






