version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip 


  test:
    executor: python/default
    steps:
      - run:
          name: run test
          command: |
            pip install pytest
            pytest test.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build









