version: 2.1
orbs:
  python: circleci/python@2.0.3
  coveralls: coveralls/coveralls@1.0.6


jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install npm
            
            coverage run -m pytest 
      - coveralls/upload:
          path_to_lcov: .coverage
          with:
            repo_token: shMx23aSB7ex6npmYqrQiad2pDTDiFHjc

      


workflows:
  execute:
    jobs:
      - build_and_test
      

    






