version: 2.1



orbs:
  python: circleci/python@2.0.3



jobs:
  build:
    executor: python/default
    step:
      - checkout
      - python/install-packages:
          pkg-manager: pip 


  test:
    executor: python/default
    step:
      - run:
          name: run test
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build









