version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    resource_class: small     
    steps:
      - checkout
      - run:
          name : raise message
          command: |
            echo 'congratulations'
            echo 'this code run porperly'





