version: 2.1
orbs:
  python: circleci/python@2.0.3
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: coverage run -m pytest 
      - coveralls/upload
      


workflows:
  execute:
    jobs:
      - build_and_test
      

    






